version: "3.9"
services:
  isuports:
    platform: linux/x86_64
    build: .
    volumes:
      - go_caches:/home/isucon/tmp
      - ./:/home/isucon/webapp/go
    command: make isuports
volumes:
  go_caches:

